name: Docker Image Builder

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} .
        docker tag ghcr.io/${{ github.repository }}/frontend:${{ github.sha }} ghcr.io/${{ github.repository }}/frontend:latest

    # Run the Docker container
    - name: Start Docker container
      run: |
        docker run -d --rm -p 3000:3000 --name frontend-container ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

    # Wait for the application to be ready
    - name: Wait for application to start
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:3000/frontend > /dev/null; then
            echo "Application is up!"
            break
          fi
          echo "Waiting for application..."
          sleep 5
        done

    # Zap scan
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'http://localhost:3000/frontend'
        fail_action: true
        allow_issue_writing: false

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT}}
        
    # Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/frontend:latest
